<template>
<div class="my_page_content">
  3t634t34t3t3erggjerogheorgherioghowerhgkerngkerhgeklrhgkehgkerhgkluwerhgiwhgwe
  uihgwkleugbweuighwehgiwebgwekgbweukgwerukhgergbierugbuiergbuiergbeuirgbergbergbegeirg
  3t634t34t3t3erggjerogheorgherioghowerhgkerngkerhgeklrhgkehgkerhgkluwerhgiwhgwe
  uihgwkleugbweuighwehgiwebgwekgbweukgwerukhgergbierugbuiergbuiergbeuirgbergbergbegeirg
  3t634t34t3t3erggjerogheorgherioghowerhgkerngkerhgeklrhgkehgkerhgkluwerhgiwhgwe
  uihgwkleugbweuighwehgiwebgwekgbweukgwerukhgergbierugbuiergbuiergbeuirgbergbergbegeirg
  3t634t34t3t3erggjerogheorgherioghowerhgkerngkerhgeklrhgkehgkerhgkluwerhgiwhgwe
  uihgwkleugbweuighwehgiwebgwekgbweukgwerukhgergbierugbuiergbuiergbeuirgbergbergbegeirg
  3t634t34t3t3erggjerogheorgherioghowerhgkerngkerhgeklrhgkehgkerhgkluwerhgiwhgwe
  uihgwkleugbweuighwehgiwebgwekgbweukgwerukhgergbierugbuiergbuiergbeuirgbergbergbegeirg
  v
  v
  3t634t34t3t3erggjerogheorgherioghowerhgkerngkerhgeklrhgkehgkerhgkluwerhgiwhgwe
  uihgwkleugbweuighwehgiwebgwekgbweukgwerukhgergbierugbuiergbuiergbeuirgbergbergbegeirgv3t634t34t3
  t3erggjerogheorgherioghowerhgkerngkerhgeklrhgkehgkerhgkluwerhgiwhgwe
  uihgwkleugbweuighwehgiwebgwekgbweukgwerukhgergbierugbuiergbuiergbeuirgbergbergbegeirg3t634t34t3t3
  erggjerogheorgherioghowerhgkerngkerhgeklrhgkehgkerhgkluwerhgiwhgwe
  uihgwkleugbweuighwehgiwebgwekgbweukgwerukhgergbierugbuiergbuiergbeuirgbergbergbegeirg
  v
  v
  v
  vv3t634t34t3t3erggjerogheorgherioghowerhgkerngkerhgeklrhgkehgkerhgkluwerhgiwhgwe
  uihgwkleugbweuighwehgiwebgwekgbweukgwerukhgergbierugbuiergbuiergbeuirgbergbergbegeirg





</div>
</template>

<script>
    export default {
        name: "mypage"
    }
</script>

<style scoped>
  .my_page_content{
    width: 100%;
    padding: 30px;
    height: 400px;
    background: white;
  }
</style>
